site_name: HollowR00t's Red Team Grimoire
site_url: https://hollowr00t.github.io/Red-Team-Grimoire/
site_description: Offensive Security Methodology and Vulnerability Research

theme:
  name: material
  logo: https://github.com/HollowR00t.png
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes

plugins:
  - search
  - awesome-pages
